Repository WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Eating-Nam-Nam, pull requests merged in 2024-01, with the labels that each got.

#55 Feat auth form
  backend/src/controllers/authControllers.js
  backend/src/models/AuthManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/src/components/singupInput/SignUpInput.jsx
  frontend/src/main.jsx
  frontend/src/pages/SignUp.jsx
  frontend/src/pages/signUp/SignUp.css
  frontend/src/pages/signUp/SignUp.jsx
  frontend/src/pages/signUp/SignUpUser.jsx
  frontend/src/services/connexion.js
Labels: Review Formateur

#57 fix footer position
  frontend/src/App.css
  frontend/src/App.jsx
Labels: Review Formateur

#51 Feat component design
  frontend/src/assets/svg/Ingredients.jsx
  frontend/src/components/FrameSvgText/FrameSvgText.jsx
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/NavbarMobile/NavbarMobile.css
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Home/Home.css
  frontend/src/pages/Home/Home.jsx
Labels: Review Formateur

#63 resolution footer
  frontend/index.css
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/footer/Footer.css
  frontend/src/pages/signUp/SignUp.css
Labels: Review Formateur

#64 Fix router
  backend/src/router.js
  frontend/src/pages/signUp/SignUpUser.jsx
Labels: Review Formateur

#67 hotfix css + background ingredients
  frontend/index.css
  frontend/src/assets/background.svg
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/NavbarMobile/NavbarMobile.css
  frontend/src/components/footer/Footer.css
  frontend/src/pages/Home/Home.css
  frontend/src/pages/Home/Home.jsx
Labels: Review Formateur

#62 Feat recipe page
  .github/workflows/lint.yml
  backend/database/data/recipe.json
  backend/database/schema.sql
  backend/seed.js
  backend/src/controllers/recipeControllers.js
  backend/src/models/RecipeManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/src/components/recipes/RecipeCard.jsx
  frontend/src/components/recipes/RecipeList.jsx
  frontend/src/main.jsx
  frontend/src/pages/Recipes.jsx
Labels: Review Formateur

#69 Ajour de unique pour mail de auth et de email() pour joi
  backend/database/schema.sql
  backend/src/middlewareValidation/middlewareAuth.js
Labels: Review Formateur

#68 About page
  frontend/src/assets/greg.png
  frontend/src/assets/leslie.png
  frontend/src/assets/logo.svg
  frontend/src/assets/thib.png
  frontend/src/assets/val.png
  frontend/src/main.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/About/About.css
  frontend/src/pages/About/About.jsx
Labels: Review Formateur

#70 Fix route regime pour le select
  backend/src/models/RegimeManager.js
  backend/src/tables.js
Labels: Review Formateur

#72 About -- Feature exceptionnelle + lien github
  frontend/src/pages/About/About.css
  frontend/src/pages/About/About.jsx
Labels: Review Formateur

#71 Page 404
  frontend/src/assets/saumon.png
  frontend/src/main.jsx
  frontend/src/pages/Page404/Page404.css
  frontend/src/pages/Page404/Page404.jsx
Labels: Review Formateur

#75 Connexion user + role + admin + navbar role + hotfix css
  backend/src/app.js
  backend/src/controllers/authControllers.js
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/formingredients/FormIngredients.css
  frontend/src/components/formingredients/FormIngredients.jsx
  frontend/src/contexts/Auth.jsx
  frontend/src/main.jsx
  frontend/src/pages/About/About.css
  frontend/src/pages/admin/Admin.jsx
  frontend/src/pages/logIn/LogIn.jsx
Labels: Review Formateur

#76 Récupérer info user
  backend/src/controllers/authControllers.js
  backend/src/controllers/userControllers.js
  backend/src/models/AuthManager.js
  backend/src/models/UserManager.js
  backend/src/router.js
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/contexts/Auth.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/pages/logIn/LogIn.jsx
  frontend/src/pages/signUp/SignUp.jsx
  frontend/src/pages/signUpUser/SignUpUser.jsx
Labels: Review Formateur

#74 css recettes et ajout coeur favoris
  backend/database/schema.sql
  backend/src/controllers/favoriteControllers.js
  backend/src/models/FavoriteManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/package.json
  frontend/src/components/favorite/Fav.css
  frontend/src/components/favorite/Favorite.jsx
  frontend/src/components/favorite/Hearth.jsx
  frontend/src/components/recipes/RecipeCard.jsx
  frontend/src/components/recipes/RecipeList.jsx
  frontend/src/components/recipes/Recipes.css
  frontend/src/main.jsx
  frontend/src/pages/favorite/Favorites.jsx
Labels: Review Formateur, MH en relecture

#79 Page_recipe by id
  frontend/src/assets/svg/Fork.svg
  frontend/src/assets/svg/Person.svg
  frontend/src/assets/svg/Time.svg
  frontend/src/main.jsx
  frontend/src/pages/recipe/Recipe.css
  frontend/src/pages/recipe/Recipe.jsx
Labels: Review Formateur

#81 Modification CSS Formulaire, Ajout images a la data, creation afficha…
  backend/database/data/eatingNamNam.json
  backend/src/controllers/ingredientsControllers.js
  backend/src/models/IngredientsManager.js
  backend/src/router.js
  frontend/src/components/formingredients/FormIngredients.css
  frontend/src/components/ingredients/Ingredient.css
  frontend/src/components/ingredients/IngredientCard.jsx
  frontend/src/components/ingredients/IngredientList.jsx
  frontend/src/main.jsx
  frontend/src/pages/Ingredients.jsx
Labels: Review Formateur, MH en relecture

#80 Hotfix NavBar + mobile
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/NavbarMobile/NavbarMobile.css
  frontend/src/components/NavbarMobile/NavbarMobile.jsx
Labels: Review Formateur

#82 Feat create prfil
  backend/src/controllers/authControllers.js
  backend/src/controllers/userControllers.js
  backend/src/models/AuthManager.js
  backend/src/models/UserManager.js
  frontend/src/main.jsx
  frontend/src/pages/Profile/Profile.css
  frontend/src/pages/Profile/Profile.jsx
Labels: Review Formateur

#84 mise en place et memorisation des cookies,ajout de jwt
  backend/package.json
  backend/src/app.js
  backend/src/controllers/authControllers.js
  backend/src/controllers/favoriteControllers.js
  backend/src/middleware/checkCredentials.js
  backend/src/models/FavoriteManager.js
  backend/src/router.js
  backend/src/services/jwt.js
  frontend/src/components/favorite/Hearth.jsx
  frontend/src/services/connexion.js
Labels: Review Formateur, MH en relecture

#85 Mise en place du dashboard pour les graphiques
  backend/src/controllers/userControllers.js
  backend/src/models/UserManager.js
  backend/src/router.js
  frontend/package.json
  frontend/src/assets/buttonDashboard.png
  frontend/src/assets/buttonManagement.png
  frontend/src/components/dashboard/Dashboard.css
  frontend/src/components/dashboard/Dashboard.jsx
  frontend/src/components/management/Management.jsx
  frontend/src/components/navbarAdmin/NavbarAdmin.jsx
  frontend/src/components/usermanagement/UserManagement.css
  frontend/src/components/usermanagement/UserManagement.jsx
  frontend/src/main.jsx
  frontend/src/pages/admin/Admin.css
  frontend/src/pages/admin/Admin.jsx
Labels: Team Review

#86 Feat formulaire2
  frontend/src/components/ingredients/Ingredient.css
Labels: Review Formateur

#87 navbar OK
  frontend/src/components/Navbar/Navbar.css
Labels: Review Formateur

#88 Raccord sur userManager suite à un petit caca
  backend/src/models/UserManager.js
Labels: Review Formateur

#89 Fix login et accès admin
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/usermanagement/UserManagement.jsx
  frontend/src/pages/admin/Admin.jsx
Labels: Review Formateur, MH en relecture

#92 recuperation de la data recipe retrait du faker, ajout lien photo
  backend/database/data/eatingNamNam.json
  backend/database/data/recipe.json
  backend/database/schema.sql
  backend/seed.js
  frontend/package-lock.json
Labels: Review Formateur

#90 Correctif MVC table ingrédients
  backend/src/controllers/ingredientControllers.js
  backend/src/controllers/ingredientsControllers.js
  backend/src/models/IngredientManager.js
  backend/src/models/IngredientsManager.js
  backend/src/router.js
Labels: Review Formateur

#91 css Ingredients + recipes frames + responsive
  frontend/index.css
  frontend/src/assets/svg/Difficulty.svg
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/ingredients/Ingredient.css
  frontend/src/components/ingredients/IngredientCard.jsx
  frontend/src/components/ingredients/IngredientList.jsx
  frontend/src/components/recipes/RecipeCard.jsx
  frontend/src/components/recipes/RecipeList.jsx
  frontend/src/components/recipes/Recipes.css
Labels: Review Formateur

#94 Ingredientmanagement
  backend/src/controllers/ingredientControllers.js
  backend/src/models/IngredientManager.js
  backend/src/router.js
  frontend/src/components/ingredientmanagement/IngredientManagement.css
  frontend/src/components/ingredientmanagement/IngredientManagement.jsx
  frontend/src/components/management/Management.css
  frontend/src/components/management/Management.jsx
Labels: Review Formateur

#98 css form Ingredients
  frontend/src/components/formingredients/FormIngredients.css
  frontend/src/components/formingredients/FormIngredients.jsx
Labels: Review Formateur

#100 Filtres opérationnels sur les recettes et modification de la data po…
  backend/database/data/recipe.json
  backend/database/data/regimes.json
  frontend/src/components/recipes/RecipeCard.jsx
  frontend/src/components/recipes/RecipeSelect.jsx
  frontend/src/components/recipes/Recipes.css
Labels: Review Formateur
